additionalStopWords = ["Programação", "Conhecimento","Facilidade", 
"Responsabilidades","Qualificações", "Desejável", "Requisitos", 
"Atividades", "Diferencial", "Ser", "de", "em", "e", "framework", 
"como","formação","time","cursando","cada", "nosso", "que",
"linguagens","ciências","graduação","atuar","office","exigidas",
"realizar","correlatos","fornecedores","neste","projetos","ter",
"um","sermos","jeito","forte","outras","informação","computação",
"trabalhar","home","será","constante","novas","esperamos","mais",
"vez","cursos","considerado","atuação""outras", "juntos","área",
"na","à","não","são","diferentes","estabelecidos","diversidade",
"utilizando","estar","serão","nosso","elaborar","dentro","concluído",
"menos","versão","indústrias","divertido","enriquece","suas","jeito", 
"equivalente","relacionais","integração","contínua","sejamos","quais",
"diferenças","Seu","suportar","aderentes","Estudar","assim","temas",
"às","Ao","nós","Pré","Abordagem","atender","fortes","melhoria",
"nossos","nossa","nossas","necessidades","tecnologias","main",
"sermos","entre","dos","para","etc","conhecimentos","da","código",
"atuado","que","apoiar","seguir","acreditamos","atuação","mesmos",
"indentificar","perfil","trabalho","ler","sobre","meses","geral",
"acostumado","grande","definição","você","liberdade","boa","preza",
"serviços","atrás","erros","existentes","pela","evolução","multi",
"controle","avançado","avançados","habituado","Buscar","Vivência",
"Domínio","códigos","funcional","efetuar","alguma","colaborar",
"Dar","técnica","Sólidos","empático","criando","identificar",
"Participar","internos","integrado","reuniões","proativo","Eng",
"ambientes","construir","Entily","importantíssimas"]